import { PhoneAttributes } from 'models/Phone';

export type PredefinedParticipant = {
  id: string;
  firstName: Nullable<string>;
  lastName: Nullable<string>;
  fullName: Nullable<string>;
  phone: Nullable<PhoneAttributes>;
  externalId: Nullable<string>;
  email: Nullable<string>;
  slug: string;
  autoInvitation: boolean;
  smsNotification: boolean;
  emailNotification: boolean;
  smsInvitationSentAt: Nullable<string>;
  emailInvitationSentAt: Nullable<string>;
  healthClinicId: Nullable<string>;
  active: boolean;
  emailAutogenerated: boolean;
};
