export const LOG_IN_USER = 'app/auth/LOG_IN_USER';
export const LOG_OUT = 'app/auth/LOG_OUT';

export const LOG_IN_GUEST = 'app/auth/LOG_IN_GUEST';

export const EDIT_USER_REQUEST = 'app/auth/EDIT_USER_REQUEST';
export const EDIT_USER_SUCCESS = 'app/auth/EDIT_USER_SUCCESS';
export const EDIT_USER_ERROR = 'app/auth/EDIT_USER_ERROR';

export const CHANGE_PASSWORD_REQUEST = 'app/auth/CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'app/auth/CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'app/auth/CHANGE_PASSWORD_ERROR';

export const CHANGE_EMAIL_REQUEST = 'app/auth/CHANGE_EMAIL_REQUEST';
export const CHANGE_EMAIL_SUCCESS = 'app/auth/CHANGE_EMAIL_SUCCESS';
export const CHANGE_EMAIL_ERROR = 'app/auth/CHANGE_EMAIL_ERROR';

export const ADD_AVATAR_REQUEST = 'app/auth/ADD_AVATAR_REQUEST';
export const ADD_AVATAR_SUCCESS = 'app/auth/ADD_AVATAR_SUCCESS';
export const ADD_AVATAR_ERROR = 'app/auth/ADD_AVATAR_ERROR';

export const DELETE_AVATAR_REQUEST = 'app/auth/DELETE_AVATAR_REQUEST';
export const DELETE_AVATAR_SUCCESS = 'app/auth/DELETE_AVATAR_SUCCESS';
export const DELETE_AVATAR_ERROR = 'app/auth/DELETE_AVATAR_ERROR';

export const CHANGE_PHONE_NUMBER_REQUEST =
  'app/auth/CHANGE_PHONE_NUMBER_REQUEST';
export const CHANGE_PHONE_NUMBER_SUCCESS =
  'app/auth/CHANGE_PHONE_NUMBER_SUCCESS';
export const CHANGE_PHONE_NUMBER_ERROR = 'app/auth/CHANGE_PHONE_NUMBER_ERROR';

export const CONFIRM_PHONE_NUMBER_REQUEST =
  'app/auth/CONFIRM_PHONE_NUMBER_REQUEST';
export const CONFIRM_PHONE_NUMBER_SUCCESS =
  'app/auth/CONFIRM_PHONE_NUMBER_SUCCESS';
export const CONFIRM_PHONE_NUMBER_ERROR = 'app/auth/CONFIRM_PHONE_NUMBER_ERROR';

export const SEND_SMS_TOKEN_REQUEST = 'app/auth/SEND_SMS_TOKEN_REQUEST';
export const SEND_SMS_TOKEN_SUCCESS = 'app/auth/SEND_SMS_TOKEN_SUCCESS';
export const SEND_SMS_TOKEN_ERROR = 'app/auth/SEND_SMS_TOKEN_ERROR';

export const CHANGE_NOTIFICATIONS_SETTINGS_REQUEST =
  'app/auth/CHANGE_NOTIFICATIONS_SETTINGS_REQUEST';
export const CHANGE_NOTIFICATIONS_SETTINGS_SUCCESS =
  'app/auth/CHANGE_NOTIFICATIONS_SETTINGS_SUCCESS';
export const CHANGE_NOTIFICATIONS_SETTINGS_ERROR =
  'app/auth/CHANGE_NOTIFICATIONS_SETTINGS_ERROR';

export const CHANGE_ERROR_STATUS = 'app/auth/CHANGE_ERROR_STATUS';
