export const FETCH_SESSIONS_REQUEST = 'app/Dashboard/FETCH_SESSIONS_REQUEST';
export const FETCH_SESSIONS_SUCCESS = 'app/Dashboard/FETCH_SESSIONS_SUCCESS';
export const FETCH_SESSIONS_ERROR = 'app/Dashboard/CREATE_SESSION_ERROR';

export const FETCH_QUESTION_GROUPS_REQUEST =
  'app/Dashboard/FETCH_QUESTION_GROUPS_REQUEST';
export const FETCH_QUESTION_GROUPS_SUCCESS =
  'app/Dashboard/FETCH_QUESTION_GROUPS_SUCCESS';
export const FETCH_QUESTION_GROUPS_ERROR =
  'app/Dashboard/FETCH_QUESTION_GROUPS_ERROR';

export const CHANGE_VIEW = 'app/Dashboard/CHANGE_VIEW';
