export const FETCH_PROBLEM_REQUEST = 'app/Dashboard/FETCH_PROBLEM_REQUEST';
export const FETCH_PROBLEM_SUCCESS = 'app/Dashboard/FETCH_PROBLEM_SUCCESS';
export const FETCH_PROBLEM_ERROR = 'app/Dashboard/FETCH_PROBLEM_ERROR';

export const SEND_PROBLEM_CSV_REQUEST =
  'app/Dashboard/SEND_PROBLEM_CSV_REQUEST';
export const SEND_PROBLEM_CSV_SUCCESS =
  'app/Dashboard/SEND_PROBLEM_CSV_SUCCESS';
export const SEND_PROBLEM_CSV_ERROR = 'app/Dashboard/SEND_PROBLEM_CSV_ERROR';

export const CREATE_PROBLEM_REQUEST = 'app/Dashboard/CREATE_PROBLEM_REQUEST';
export const CREATE_PROBLEM_SUCCESS = 'app/Dashboard/CREATE_PROBLEM_SUCCESS';
export const CREATE_PROBLEM_ERROR = 'app/Dashboard/CREATE_PROBLEM_ERROR';

export const EDIT_PROBLEM_REQUEST = 'app/Dashboard/EDIT_PROBLEM_REQUEST';
export const EDIT_PROBLEM_SUCCESS = 'app/Dashboard/EDIT_PROBLEM_SUCCESS';
export const EDIT_PROBLEM_ERROR = 'app/Dashboard/EDIT_PROBLEM_ERROR';

export const COPY_INTERVENTION_REQUEST =
  'app/Dashboard/COPY_INTERVENTION_REQUEST';
export const COPY_INTERVENTION_SUCCESS =
  'app/Dashboard/COPY_INTERVENTION_SUCCESS';
export const COPY_INTERVENTION_ERROR = 'app/Dashboard/COPY_INTERVENTION_ERROR';

export const REORDER_INTERVENTION_LIST =
  'app/Dashboard/REORDER_INTERVENTION_LIST';
export const REORDER_INTERVENTION_LIST_SUCCESS =
  'app/Dashboard/REORDER_INTERVENTION_LIST_SUCCESS';
export const REORDER_INTERVENTION_LIST_ERROR =
  'app/Dashboard/REORDER_INTERVENTION_LIST_ERROR';

export const CHANGE_ACCESS_SETTING_REQUEST =
  'app/Dashboard/CHANGE_ACCESS_SETTING_REQUEST';
export const CHANGE_ACCESS_SETTING_SUCCESS =
  'app/Dashboard/CHANGE_ACCESS_SETTING_SUCCESS';
export const CHANGE_ACCESS_SETTING_ERROR =
  'app/Dashboard/CHANGE_ACCESS_SETTING_ERROR';

export const ENABLE_USER_ACCESS_REQUEST =
  'app/Dashboard/ENABLE_USER_ACCESS_REQUEST';
export const ENABLE_USER_ACCESS_SUCCESS =
  'app/Dashboard/ENABLE_USER_ACCESS_SUCCESS';
export const ENABLE_USER_ACCESS_ERROR =
  'app/Dashboard/ENABLE_USER_ACCESS_ERROR';

export const FETCH_USERS_WITH_ACCESS_REQUEST =
  'app/Dashboard/FETCH_USERS_WITH_ACCESS_REQUEST';
export const FETCH_USERS_WITH_ACCESS_SUCCESS =
  'app/Dashboard/FETCH_USERS_WITH_ACCESS_SUCCESS';
export const FETCH_USERS_WITH_ACCESS_ERROR =
  'app/Dashboard/FETCH_USERS_WITH_ACCESS_ERROR';

export const REVOKE_USER_ACCESS_REQUEST =
  'app/Dashboard/REVOKE_USER_ACCESS_REQUEST';
export const REVOKE_USER_ACCESS_SUCCESS =
  'app/Dashboard/REVOKE_USER_ACCESS_SUCCESS';
export const REVOKE_USER_ACCESS_ERROR =
  'app/Dashboard/REVOKE_USER_ACCESS_ERROR';

// create intervention constants
export const CREATE_INTERVENTION_REQUEST = 'app/CREATE_INTERVENTION_REQUEST';
export const CREATE_INTERVENTION_SUCCESS = 'app/CREATE_INTERVENTION_SUCCESS';
export const CREATE_INTERVENTION_ERROR = 'app/CREATE_INTERVENTION_ERROR';
