export const CREATE_ORGANIZATION_REQUEST =
  'app/organizations/CREATE_ORGANIZATION_REQUEST';
export const CREATE_ORGANIZATION_SUCCESS =
  'app/organizations/CREATE_ORGANIZATION_SUCCESS';
export const CREATE_ORGANIZATION_ERROR =
  'app/organizations/CREATE_ORGANIZATION_ERROR';

export const FETCH_ORGANIZATIONS_REQUEST =
  'app/organizations/FETCH_ORGANIZATIONS_REQUEST';
export const FETCH_ORGANIZATIONS_SUCCESS =
  'app/organizations/FETCH_ORGANIZATIONS_SUCCESS';
export const FETCH_ORGANIZATIONS_ERROR =
  'app/organizations/FETCH_ORGANIZATIONS_ERROR';
