export const VERIFY_TEST_LINK_TOKEN_REQUEST =
  'app/TestLinkToken/VERIFY_TEST_LINK_TOKEN_REQUEST';
export const VERIFY_TEST_LINK_TOKEN_SUCCESS =
  'app/TestLinkToken/VERIFY_TEST_LINK_TOKEN_SUCCESS';
export const VERIFY_TEST_LINK_TOKEN_ERROR =
  'app/TestLinkToken/VERIFY_TEST_LINK_TOKEN_ERROR';
