export const FETCH_ANSWERS_REQUEST = 'app/SessionMap/FETCH_ANSWERS_REQUEST';
export const FETCH_ANSWERS_SUCCESS = 'app/SessionMap/FETCH_ANSWERS_SUCCESS';
export const FETCH_ANSWERS_ERROR = 'app/SessionMap/FETCH_ANSWERS_ERROR';
