export const API_URL = 'API_URL';

export const ADMIN_EMAIL = 'ADMIN_EMAIL';
export const ADMIN_PASSWORD = 'ADMIN_PASSWORD';

export const RESEARCHER_EMAIL = 'RESEARCHER_EMAIL';
export const RESEARCHER_PASSWORD = 'RESEARCHER_PASSWORD';

export const PARTICIPANT_EMAIL = 'PARTICIPANT_EMAIL';
export const PARTICIPANT_PASSWORD = 'PARTICIPANT_PASSWORD';
