# https://circleci.com/docs/2.0/language-javascript/
version: 2
jobs:
  build_and_lint:
    docker:
      - image: circleci/node:12.16.3

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - dependency-cache-{{ .Branch }}
            - dependency-cache

      - run:
          name: Install npm
          command: npm install

      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: Lint js and css
          command: npm run lint


  test:
    docker:
      - image: circleci/node:12.16.3

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - dependency-cache-{{ .Branch }}
            - dependency-cache

      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  default:
    jobs:
      - build_and_lint
      - test:
          requires:
            - build_and_lint
          filters:
            branches:
              only:
                - master
                - dev
