# https://circleci.com/docs/2.0/language-javascript/
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.16.3

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          name: Install npm
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  lint:
    docker:
      - image: circleci/node:12.16.3

    steps:
      - checkout

      - run:
          name: Lint js and css
          command: npm run lint

  test:
    docker:
      - image: circleci/node:12.16.3

    steps:
      - checkout

      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  default:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - lint
          filters:
            branches:
              only:
                - master
                - dev
