/*
 *
 * UserList constants
 *
 */

export const FETCH_USER_REQUEST = 'app/User /FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'app/User /FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'app/User /FETCH_USER_FAILURE';

export const EDIT_OTHER_USER_REQUEST = 'app/User  /EDIT_OTHER_USER_REQUEST';
export const EDIT_OTHER_USER_SUCCESS = 'app/User  /EDIT_OTHER_USER_SUCCESS';
export const EDIT_OTHER_USER_ERROR = 'app/User  /EDIT_OTHER_USER_ERROR';

export const ADD_OTHER_USER_AVATAR_REQUEST =
  'app/User /ADD_OTHER_USER_AVATAR_REQUEST';
export const ADD_OTHER_USER_AVATAR_SUCCESS =
  'app/User /ADD_OTHER_USER_AVATAR_SUCCESS';
export const ADD_OTHER_USER_AVATAR_ERROR =
  'app/User /EDIT_OTHER_US_AVATAR_ERROR';

export const DELETE_OTHER_USER_AVATAR_REQUEST =
  'app/User /DELETE_OTHER_USER_AVATAR_REQUEST';
export const DELETE_OTHER_USER_AVATAR_SUCCESS =
  'app/User /DELETE_OTHER_USER_AVATAR_SUCCESS';
export const DELETE_OTHER_USER_AVATAR_ERROR =
  'app/User /EDIT_OTHER_US_AVATAR_ERROR';

export const CHANGE_ACTIVATE_STATUS_REQUEST =
  'app/User /CHANGE_ACTIVATE_STATUS_REQUEST';
export const CHANGE_ACTIVATE_STATUS_SUCCESS =
  'app/User /CHANGE_ACTIVATE_STATUS_SUCCESS';
export const CHANGE_ACTIVATE_STATUS_ERROR =
  'app/User /CHANGE_ACTIVATE_STATUS_ERROR';
