/*
 *
 * UserList constants
 *
 */

export const FETCH_USER = 'app/UserList/FETCH_USER';
export const FETCH_USER_SUCCESS = 'app/UserList/FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'app/UserList/FETCH_USER_FAILURE';

export const EDIT_OTHER_USER_REQUEST = 'app/UserList/EDIT_OTHER_USER_REQUEST';
export const EDIT_OTHER_USER_SUCCESS = 'app/UserList/EDIT_OTHER_USER_SUCCESS';
export const EDIT_OTHER_USER_ERROR = 'app/UserList/EDIT_OTHER_USER_ERROR';

export const ADD_OTHER_USER_AVATAR_REQUEST =
  'app/UserList/ADD_OTHER_USER_AVATAR_REQUEST';
export const ADD_OTHER_USER_AVATAR_SUCCESS =
  'app/UserList/ADD_OTHER_USER_AVATAR_SUCCESS';
export const ADD_OTHER_USER_AVATAR_ERROR =
  'app/UserList/EDIT_OTHER_US_AVATAR_ERROR';

export const DELETE_OTHER_USER_AVATAR_REQUEST =
  'app/UserList/DELETE_OTHER_USER_AVATAR_REQUEST';
export const DELETE_OTHER_USER_AVATAR_SUCCESS =
  'app/UserList/DELETE_OTHER_USER_AVATAR_SUCCESS';
export const DELETE_OTHER_USER_AVATAR_ERROR =
  'app/UserList/EDIT_OTHER_US_AVATAR_ERROR';
