export const FETCH_NAVIGATOR_SETUP_REQUEST =
  'app/NAVIGATOR_SETUP/FETCH_NAVIGATOR_SETUP_REQUEST';
export const FETCH_NAVIGATOR_SETUP_SUCCESS =
  'app/NAVIGATOR_SETUP/FETCH_NAVIGATOR_SETUP_SUCCESS';
export const FETCH_NAVIGATOR_SETUP_ERROR =
  'app/NAVIGATOR_SETUP/FETCH_NAVIGATOR_SETUP_ERROR';

export const UPDATE_NAVIGATOR_SETUP_REQUEST =
  'app/NAVIGATOR_SETUP/UPDATE_NAVIGATOR_SETUP_REQUEST';
export const UPDATE_NAVIGATOR_SETUP_SUCCESS =
  'app/NAVIGATOR_SETUP/UPDATE_NAVIGATOR_SETUP_SUCCESS';
export const UPDATE_NAVIGATOR_SETUP_ERROR =
  'app/NAVIGATOR_SETUP/UPDATE_NAVIGATOR_SETUP_ERROR';
