export const FETCH_NAVIGATOR_SETUP_REQUEST =
  'app/NAVIGATOR_SETUP/FETCH_NAVIGATOR_SETUP_REQUEST';
export const FETCH_NAVIGATOR_SETUP_SUCCESS =
  'app/NAVIGATOR_SETUP/FETCH_NAVIGATOR_SETUP_SUCCESS';
export const FETCH_NAVIGATOR_SETUP_ERROR =
  'app/NAVIGATOR_SETUP/FETCH_NAVIGATOR_SETUP_ERROR';

export const UPDATE_NAVIGATOR_SETUP_REQUEST =
  'app/NAVIGATOR_SETUP/UPDATE_NAVIGATOR_SETUP_REQUEST';
export const UPDATE_NAVIGATOR_SETUP_SUCCESS =
  'app/NAVIGATOR_SETUP/UPDATE_NAVIGATOR_SETUP_SUCCESS';
export const UPDATE_NAVIGATOR_SETUP_ERROR =
  'app/NAVIGATOR_SETUP/UPDATE_NAVIGATOR_SETUP_ERROR';

export const ADD_PARTICIPANT_LINK_REQUEST =
  'app/NAVIGATOR_SETUP/ADD_PARTICIPANT_LINK_REQUEST';
export const ADD_PARTICIPANT_LINK_SUCCESS =
  'app/NAVIGATOR_SETUP/ADD_PARTICIPANT_LINK_SUCCESS';
export const ADD_PARTICIPANT_LINK_ERROR =
  'app/NAVIGATOR_SETUP/ADD_PARTICIPANT_LINK_ERROR';

export const REMOVE_PARTICIPANT_LINK_REQUEST =
  'app/NAVIGATOR_SETUP/REMOVE_PARTICIPANT_LINK_REQUEST';
export const REMOVE_PARTICIPANT_LINK_SUCCESS =
  'app/NAVIGATOR_SETUP/REMOVE_PARTICIPANT_LINK_SUCCESS';
export const REMOVE_PARTICIPANT_LINK_ERROR =
  'app/NAVIGATOR_SETUP/REMOVE_PARTICIPANT_LINK_ERROR';

export const UPDATE_PARTICIPANT_LINK_REQUEST =
  'app/NAVIGATOR_SETUP/UPDATE_PARTICIPANT_LINK_REQUEST';
export const UPDATE_PARTICIPANT_LINK_SUCCESS =
  'app/NAVIGATOR_SETUP/UPDATE_PARTICIPANT_LINK_SUCCESS';
export const UPDATE_PARTICIPANT_LINK_ERROR =
  'app/NAVIGATOR_SETUP/UPDATE_PARTICIPANT_LINK_ERROR';

export const INVITE_NAVIGATOR_BY_EMAIL_REQUEST =
  'app/NAVIGATOR_SETUP/INVITE_NAVIGATOR_BY_EMAIL_REQUEST';
export const INVITE_NAVIGATOR_BY_EMAIL_SUCCESS =
  'app/NAVIGATOR_SETUP/INVITE_NAVIGATOR_BY_EMAIL_SUCCESS';
export const INVITE_NAVIGATOR_BY_EMAIL_ERROR =
  'app/NAVIGATOR_SETUP/INVITE_NAVIGATOR_BY_EMAIL_ERROR';
