export const FETCH_INTERVENTION_REQUEST =
  'app/Dashboard/FETCH_INTERVENTION_REQUEST';
export const FETCH_INTERVENTION_SUCCESS =
  'app/Dashboard/FETCH_INTERVENTION_SUCCESS';
export const FETCH_INTERVENTION_ERROR =
  'app/Dashboard/FETCH_INTERVENTION_ERROR';

export const SEND_INTERVENTION_CSV_REQUEST =
  'app/Dashboard/SEND_INTERVENTION_CSV_REQUEST';
export const SEND_INTERVENTION_CSV_SUCCESS =
  'app/Dashboard/SEND_INTERVENTION_CSV_SUCCESS';
export const SEND_INTERVENTION_CSV_ERROR =
  'app/Dashboard/SEND_INTERVENTION_CSV_ERROR';

export const CREATE_INTERVENTION_REQUEST =
  'app/Dashboard/CREATE_INTERVENTION_REQUEST';
export const CREATE_INTERVENTION_SUCCESS =
  'app/Dashboard/CREATE_INTERVENTION_SUCCESS';
export const CREATE_INTERVENTION_ERROR =
  'app/Dashboard/CREATE_INTERVENTION_ERROR';

export const EDIT_INTERVENTION_REQUEST =
  'app/Dashboard/EDIT_INTERVENTION_REQUEST';
export const EDIT_INTERVENTION_SUCCESS =
  'app/Dashboard/EDIT_INTERVENTION_SUCCESS';
export const EDIT_INTERVENTION_ERROR = 'app/Dashboard/EDIT_INTERVENTION_ERROR';

export const COPY_SESSION_REQUEST = 'app/Dashboard/COPY_SESSION_REQUEST';
export const COPY_SESSION_SUCCESS = 'app/Dashboard/COPY_SESSION_SUCCESS';
export const COPY_SESSION_ERROR = 'app/Dashboard/COPY_SESSION_ERROR';

export const REORDER_SESSION_LIST = 'app/Dashboard/REORDER_SESSION_LIST';
export const REORDER_SESSION_LIST_SUCCESS =
  'app/Dashboard/REORDER_SESSION_LIST_SUCCESS';
export const REORDER_SESSION_LIST_ERROR =
  'app/Dashboard/REORDER_SESSION_LIST_ERROR';

export const UPDATE_SESSION_SETTINGS_REQUEST =
  'app/Dashboard/UPDATE_SESSION_SETTINGS_REQUEST';
export const UPDATE_SESSION_SETTINGS_SUCCESS =
  'app/Dashboard/UPDATE_SESSION_SETTINGS_SUCCESS';
export const UPDATE_SESSION_SETTINGS_ERROR =
  'app/Dashboard/UPDATE_SESSION_SETTINGS_ERROR';

export const CHANGE_CURRENT_SESSION =
  'app/containers/InterventionDetailsPage/CHANGE_CURRENT_SESSION';

export const ENABLE_USER_ACCESS_REQUEST =
  'app/Dashboard/ENABLE_USER_ACCESS_REQUEST';
export const ENABLE_USER_ACCESS_SUCCESS =
  'app/Dashboard/ENABLE_USER_ACCESS_SUCCESS';
export const ENABLE_USER_ACCESS_ERROR =
  'app/Dashboard/ENABLE_USER_ACCESS_ERROR';

export const FETCH_USERS_WITH_ACCESS_REQUEST =
  'app/Dashboard/FETCH_USERS_WITH_ACCESS_REQUEST';
export const FETCH_USERS_WITH_ACCESS_SUCCESS =
  'app/Dashboard/FETCH_USERS_WITH_ACCESS_SUCCESS';
export const FETCH_USERS_WITH_ACCESS_ERROR =
  'app/Dashboard/FETCH_USERS_WITH_ACCESS_ERROR';

export const REVOKE_USER_ACCESS_REQUEST =
  'app/Dashboard/REVOKE_USER_ACCESS_REQUEST';
export const REVOKE_USER_ACCESS_SUCCESS =
  'app/Dashboard/REVOKE_USER_ACCESS_SUCCESS';
export const REVOKE_USER_ACCESS_ERROR =
  'app/Dashboard/REVOKE_USER_ACCESS_ERROR';

// create session constants
export const CREATE_SESSION_REQUEST = 'app/CREATE_SESSION_REQUEST';
export const CREATE_SESSION_SUCCESS = 'app/CREATE_SESSION_SUCCESS';
export const CREATE_SESSION_ERROR = 'app/CREATE_SESSION_ERROR';

// session invitation
export const SEND_SESSION_INVITE_REQUEST = 'app/SEND_SESSION_INVITE_REQUEST';
export const SEND_SESSION_INVITE_SUCCESS = 'app/SEND_SESSION_INVITE_SUCCESS';
export const SEND_SESSION_INVITE_ERROR = 'app/SEND_SESSION_INVITE_ERROR';

export const RESEND_SESSION_INVITE_REQUEST =
  'app/RESEND_SESSION_INVITE_REQUEST';

// intervention invitation
export const FETCH_INTERVENTION_INVITES_REQUEST =
  'app/FETCH_INTERVENTION_INVITES_REQUEST';
export const FETCH_INTERVENTION_INVITES_SUCCESS =
  'app/FETCH_INTERVENTION_INVITES_SUCCESS';
export const FETCH_INTERVENTION_INVITES_ERROR =
  'app/FETCH_INTERVENTION_INVITES_ERROR';

export const SEND_INTERVENTION_INVITE_REQUEST =
  'app/SEND_INTERVENTION_INVITE_REQUEST';
export const SEND_INTERVENTION_INVITE_SUCCESS =
  'app/SEND_INTERVENTION_INVITE_SUCCESS';
export const SEND_INTERVENTION_INVITE_ERROR =
  'app/SEND_INTERVENTION_INVITE_ERROR';

export const RESEND_INTERVENTION_INVITE_REQUEST =
  'app/RESEND_INTERVENTION_INVITE_REQUEST';

export const FETCH_SESSION_EMAILS_REQUEST = 'app/FETCH_SESSION_EMAILS_REQUEST';
export const FETCH_SESSION_EMAILS_SUCCESS = 'app/FETCH_SESSION_EMAILS_SUCCESS';
export const FETCH_SESSION_EMAILS_ERROR = 'app/FETCH_SESSION_EMAILS_ERROR';

export const DELETE_SESSION_REQUEST = 'app/DELETE_SESSION_REQUEST';
export const DELETE_SESSION_SUCCESS = 'app/DELETE_SESSION_SUCCESS';
export const DELETE_SESSION_ERROR = 'app/DELETE_SESSION_ERROR';

export const EXTERNAL_COPY_SESSION_REQUEST =
  'app/Dashboard/EXTERNAL_COPY_SESSION_REQUEST';
export const EXTERNAL_COPY_SESSION_SUCCESS =
  'app/Dashboard/EXTERNAL_COPY_SESSION_SUCCESS';
export const EXTERNAL_COPY_SESSION_ERROR =
  'app/Dashboard/EXTERNAL_COPY_SESSION_ERROR';

export const ADD_INTERVENTION_LOGO_REQUEST =
  'app/Dashboard/ADD_INTERVENTION_LOGO_REQUEST';
export const ADD_INTERVENTION_LOGO_SUCCESS =
  'app/Dashboard/ADD_INTERVENTION_LOGO_SUCCESS';
export const ADD_INTERVENTION_LOGO_ERROR =
  'app/Dashboard/ADD_INTERVENTION_LOGO_ERROR';

export const DELETE_INTERVENTION_LOGO_REQUEST =
  'app/Dashboard/DELETE_INTERVENTION_LOGO_REQUEST';
export const DELETE_INTERVENTION_LOGO_SUCCESS =
  'app/Dashboard/DELETE_INTERVENTION_LOGO_SUCCESS';
export const DELETE_INTERVENTION_LOGO_ERROR =
  'app/Dashboard/DELETE_INTERVENTION_LOGO_ERROR';

export const UPDATE_INTERVENTION_LOGO_REQUEST =
  'app/Dashboard/UPDATE_INTERVENTION_LOGO_REQUEST';
export const UPDATE_INTERVENTION_LOGO_SUCCESS =
  'app/Dashboard/UPDATE_INTERVENTION_LOGO_SUCCESS';
export const UPDATE_INTERVENTION_LOGO_ERROR =
  'app/Dashboard/UPDATE_INTERVENTION_LOGO_ERROR';

export const TRANSLATE_INTERVENTION_REQUEST =
  'app/Dashboard/TRANSLATE_INTERVENTION_REQUEST';
export const TRANSLATE_INTERVENTION_SUCCESS =
  'app/Dashboard/TRANSLATE_INTERVENTION_SUCCESS';
export const TRANSLATE_INTERVENTION_ERROR =
  'app/Dashboard/TRANSLATE_INTERVENTION_ERROR';

export const ADD_INTERVENTION_ATTACHMENTS_ERROR =
  'app/Dashboard/ADD_INTERVENTION_ATTACHMENTS_ERROR';
export const ADD_INTERVENTION_ATTACHMENTS_REQUEST =
  'app/Dashboard/ADD_INTERVENTION_ATTACHMENTS_REQUEST';
export const ADD_INTERVENTION_ATTACHMENTS_SUCCESS =
  'app/Dashboard/ADD_INTERVENTION_ATTACHMENTS_SUCCESS';
export const DELETE_INTERVENTION_ATTACHMENT_REQUEST =
  'app/Dashboard/DELETE_INTERVENTION_ATTACHMENT_REQUEST';
export const DELETE_INTERVENTION_ATTACHMENT_SUCCESS =
  'app/Dashboard/DELETE_INTERVENTION_ATTACHMENT_SUCCESS';

export const GENERATE_CONVERSATIONS_TRANSCRIPT_REQUEST =
  'app/Dashboard/GENERATE_CONVERSATIONS_TRANSCRIPT_REQUEST';
export const GENERATE_CONVERSATIONS_TRANSCRIPT_SUCCESS =
  'app/Dashboard/GENERATE_CONVERSATIONS_TRANSCRIPT_SUCCESS';
export const GENERATE_CONVERSATIONS_TRANSCRIPT_ERROR =
  'app/Dashboard/GENERATE_CONVERSATIONS_TRANSCRIPT_ERROR';

export const UPDATE_INTERVENTION_CONVERSATIONS_TRANSCRIPT =
  'app/Dashboard/UPDATE_INTERVENTION_CONVERSATIONS_TRANSCRIPT';

export const EXPORT_INTERVENTION_REQUEST =
  'app/Dashboard/EXPORT_INTERVENTION_REQUEST';
export const EXPORT_INTERVENTION_SUCCESS =
  'app/Dashboard/EXPORT_INTERVENTION_SUCCESS';
export const EXPORT_INTERVENTION_ERROR =
  'app/Dashboard/EXPORT_INTERVENTION_ERROR';
