export const FETCH_PROBLEM_REQUEST = 'app/Dashboard/FETCH_PROBLEM_REQUEST';
export const FETCH_PROBLEM_SUCCESS = 'app/Dashboard/FETCH_PROBLEM_SUCCESS';
export const FETCH_PROBLEM_ERROR = 'app/Dashboard/FETCH_PROBLEM_ERROR';

export const SEND_PROBLEM_CSV_REQUEST =
  'app/Dashboard/SEND_PROBLEM_CSV_REQUEST';
export const SEND_PROBLEM_CSV_SUCCESS =
  'app/Dashboard/SEND_PROBLEM_CSV_SUCCESS';
export const SEND_PROBLEM_CSV_ERROR = 'app/Dashboard/SEND_PROBLEM_CSV_ERROR';

export const CREATE_PROBLEM_REQUEST = 'app/Dashboard/CREATE_PROBLEM_REQUEST';
export const CREATE_PROBLEM_SUCCESS = 'app/Dashboard/CREATE_PROBLEM_SUCCESS';
export const CREATE_PROBLEM_ERROR = 'app/Dashboard/CREATE_PROBLEM_ERROR';

export const EDIT_PROBLEM_REQUEST = 'app/Dashboard/EDIT_PROBLEM_REQUEST';
export const EDIT_PROBLEM_SUCCESS = 'app/Dashboard/EDIT_PROBLEM_SUCCESS';
export const EDIT_PROBLEM_ERROR = 'app/Dashboard/EDIT_PROBLEM_ERROR';

export const COPY_SESSION_REQUEST = 'app/Dashboard/COPY_SESSION_REQUEST';
export const COPY_SESSION_SUCCESS = 'app/Dashboard/COPY_SESSION_SUCCESS';
export const COPY_SESSION_ERROR = 'app/Dashboard/COPY_SESSION_ERROR';

export const REORDER_SESSION_LIST = 'app/Dashboard/REORDER_SESSION_LIST';
export const REORDER_SESSION_LIST_SUCCESS =
  'app/Dashboard/REORDER_SESSION_LIST_SUCCESS';
export const REORDER_SESSION_LIST_ERROR =
  'app/Dashboard/REORDER_SESSION_LIST_ERROR';

export const UPDATE_SESSION_SETTINGS_REQUEST =
  'app/Dashboard/UPDATE_SESSION_SETTINGS_REQUEST';
export const UPDATE_SESSION_SETTINGS_SUCCESS =
  'app/Dashboard/UPDATE_SESSION_SETTINGS_SUCCESS';
export const UPDATE_SESSION_SETTINGS_ERROR =
  'app/Dashboard/UPDATE_SESSION_SETTINGS_ERROR';

export const CHANGE_CURRENT_SESSION =
  'app/containers/ProblemDetailsPage/CHANGE_CURRENT_INTERVENTION';
export const CHANGE_ACCESS_SETTING_REQUEST =
  'app/Dashboard/CHANGE_ACCESS_SETTING_REQUEST';
export const CHANGE_ACCESS_SETTING_SUCCESS =
  'app/Dashboard/CHANGE_ACCESS_SETTING_SUCCESS';
export const CHANGE_ACCESS_SETTING_ERROR =
  'app/Dashboard/CHANGE_ACCESS_SETTING_ERROR';

export const ENABLE_USER_ACCESS_REQUEST =
  'app/Dashboard/ENABLE_USER_ACCESS_REQUEST';
export const ENABLE_USER_ACCESS_SUCCESS =
  'app/Dashboard/ENABLE_USER_ACCESS_SUCCESS';
export const ENABLE_USER_ACCESS_ERROR =
  'app/Dashboard/ENABLE_USER_ACCESS_ERROR';

export const FETCH_USERS_WITH_ACCESS_REQUEST =
  'app/Dashboard/FETCH_USERS_WITH_ACCESS_REQUEST';
export const FETCH_USERS_WITH_ACCESS_SUCCESS =
  'app/Dashboard/FETCH_USERS_WITH_ACCESS_SUCCESS';
export const FETCH_USERS_WITH_ACCESS_ERROR =
  'app/Dashboard/FETCH_USERS_WITH_ACCESS_ERROR';

export const REVOKE_USER_ACCESS_REQUEST =
  'app/Dashboard/REVOKE_USER_ACCESS_REQUEST';
export const REVOKE_USER_ACCESS_SUCCESS =
  'app/Dashboard/REVOKE_USER_ACCESS_SUCCESS';
export const REVOKE_USER_ACCESS_ERROR =
  'app/Dashboard/REVOKE_USER_ACCESS_ERROR';

// create session constants
export const CREATE_SESSION_REQUEST = 'app/CREATE_SESSION_REQUEST';
export const CREATE_SESSION_SUCCESS = 'app/CREATE_SESSION_SUCCESS';
export const CREATE_SESSION_ERROR = 'app/CREATE_SESSION_ERROR';

// session invitation
export const SEND_SESSION_INVITE_REQUEST = 'app/SEND_SESSION_INVITE_REQUEST';
export const SEND_SESSION_INVITE_SUCCESS = 'app/SEND_SESSION_INVITE_SUCCESS';
export const SEND_SESSION_INVITE_ERROR = 'app/SEND_SESSION_INVITE_ERROR';

export const RESEND_SESSION_INVITE_REQUEST =
  'app/RESEND_SESSION_INVITE_REQUEST';

export const FETCH_SESSION_EMAILS_REQUEST = 'app/FETCH_SESSION_EMAILS_REQUEST';
export const FETCH_SESSION_EMAILS_SUCCESS = 'app/FETCH_SESSION_EMAILS_SUCCESS';
export const FETCH_SESSION_EMAILS_ERROR = 'app/FETCH_SESSION_EMAILS_ERROR';
