export const FETCH_PROBLEMS_REQUEST = 'app/Dashboard/FETCH_PROBLEMS_REQUEST';
export const FETCH_PROBLEMS_SUCCESS = 'app/Dashboard/FETCH_PROBLEMS_SUCCESS';
export const FETCH_PROBLEMS_ERROR = 'app/Dashboard/FETCH_PROBLEMS_ERROR';

export const COPY_PROBLEM_REQUEST = 'app/Dashboard/COPY_PROBLEM_REQUEST';
export const COPY_PROBLEM_SUCCESS = 'app/Dashboard/COPY_PROBLEM_SUCCESS';
export const COPY_PROBLEM_ERROR = 'app/Dashboard/COPY_PROBLEM_ERROR';
