export const RESET_PASSWORD_REQUEST = 'app/auth/RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'app/auth/RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'app/auth/RESET_PASSWORD_ERROR';
