import React from 'react';
import { useIntl } from 'react-intl';

import { PredefinedParticipant } from 'models/PredefinedParticipant';

import Row from 'components/Row';
import Button from 'components/Button';

import messages from './messages';

export type Props = {
  invitingPossible: boolean;
  participant: PredefinedParticipant;
  handleSendSmsInvitation: () => void;
  sendingSmsInvitation: boolean;
  handleSendEmailInvitation: () => void;
  sendingEmailInvitation: boolean;
};

export const SendInvitationsButtons = ({
  invitingPossible,
  participant,
  handleSendSmsInvitation,
  sendingSmsInvitation,
  handleSendEmailInvitation,
  sendingEmailInvitation,
}: Props) => {
  const { formatMessage } = useIntl();

  return (
    <Row mt={16} gap={16}>
      <Button
        width="auto"
        px={24}
        inverted
        onClick={handleSendSmsInvitation}
        loading={sendingSmsInvitation}
        disabled={
          !invitingPossible || !participant.phone || !participant.active
        }
      >
        {formatMessage(
          messages[
            participant.smsInvitationSentAt
              ? 'predefinedParticipantResendSmsInvitationButtonTitle'
              : 'predefinedParticipantSendSmsInvitationButtonTitle'
          ],
        )}
      </Button>
      <Button
        width="auto"
        px={24}
        inverted
        onClick={handleSendEmailInvitation}
        loading={sendingEmailInvitation}
        disabled={
          !invitingPossible ||
          !participant.email ||
          participant.emailAutogenerated ||
          !participant.active
        }
      >
        {formatMessage(
          messages[
            participant.emailInvitationSentAt
              ? 'predefinedParticipantResendEmailInvitationButtonTitle'
              : 'predefinedParticipantSendEmailInvitationButtonTitle'
          ],
        )}
      </Button>
    </Row>
  );
};
