export const SET_NEW_PASSWORD_REQUEST = 'app/auth/SET_NEW_PASSWORD_REQUEST';
export const SET_NEW_PASSWORD_SUCCESS = 'app/auth/SET_NEW_PASSWORD_SUCCESS';
export const SET_NEW_PASSWORD_ERROR = 'app/auth/SET_NEW_PASSWORD_ERROR';
