// get intervention constants
export const GET_INTERVENTION_REQUEST = 'app/GET_INTERVENTION_REQUEST';
export const GET_INTERVENTION_SUCCESS = 'app/GET_INTERVENTION_SUCCESS';
export const GET_INTERVENTION_ERROR = 'app/GET_INTERVENTION_ERROR';

// edit intervention constants
export const EDIT_INTERVENTION_REQUEST = 'app/EDIT_INTERVENTION_REQUEST';
export const EDIT_INTERVENTION_SUCCESS = 'app/EDIT_INTERVENTION_SUCCESS';
export const EDIT_INTERVENTION_ERROR = 'app/EDIT_INTERVENTION_ERROR';
