/*
 *
 * RegisterPage constants
 *
 */

export const REGISTER_PARTICIPANT_REQUEST =
  'app/RegisterPage/REGISTER_PARTICIPANT_REQUEST';
export const REGISTER_PARTICIPANT_SUCCESS =
  'app/RegisterPage/REGISTER_PARTICIPANT_SUCCESS';
export const REGISTER_PARTICIPANT_ERROR =
  'app/RegisterPage/REGISTER_PARTICIPANT_ERROR';

export const REGISTER_RESEARCHER_REQUEST =
  'app/RegisterPage/REGISTER_RESEARCHER_REQUEST';
export const REGISTER_RESEARCHER_SUCCESS =
  'app/RegisterPage/REGISTER_RESEARCHER_SUCCESS';
export const REGISTER_RESEARCHER_ERROR =
  'app/RegisterPage/REGISTER_RESEARCHER_ERROR';
