/*
 *
 * RegisterPage constants
 *
 */

export const REGISTER_PARTICIPANT_REQUEST =
  'app/RegisterPage/REGISTER_PARTICIPANT_REQUEST';
export const REGISTER_PARTICIPANT_SUCCESS =
  'app/RegisterPage/REGISTER_PARTICIPANT_SUCCESS';
export const REGISTER_PARTICIPANT_ERROR =
  'app/RegisterPage/REGISTER_PARTICIPANT_ERROR';

export const REGISTER_FROM_INVITATION_REQUEST =
  'app/RegisterPage/REGISTER_FROM_INVITATION_REQUEST';
export const REGISTER_FROM_INVITATION_SUCCESS =
  'app/RegisterPage/REGISTER_FROM_INVITATION_SUCCESS';
export const REGISTER_FROM_INVITATION_ERROR =
  'app/RegisterPage/REGISTER_FROM_INVITATION_ERROR';

export const CLEAR_ERRORS = 'app/RegisterPage/CLEAR_ERRORS';
