const MILLISECONDS_IN_SECOND = 1000;
const SECONDS_IN_MINUTE = 60;
const MINUTES_TO_LOGOUT = 15;

export const TIME_TO_LOGOUT =
  MILLISECONDS_IN_SECOND * SECONDS_IN_MINUTE * MINUTES_TO_LOGOUT;

export const PING_THROTTLE_INTERVAL = 60 * MILLISECONDS_IN_SECOND;
export const ACTIVITY_EVENTS = ['keydown', 'click', 'touchstart'];
