export const COPY_QUESTIONS_REQUEST =
  'app/EditInterventionPage/COPY_QUESTIONS_REQUEST';
export const COPY_QUESTIONS_SUCCESS =
  'app/EditInterventionPage/COPY_QUESTIONS_SUCCESS';
export const COPY_QUESTIONS_ERROR =
  'app/EditInterventionPage/COPY_QUESTIONS_ERROR';

export const DELETE_QUESTIONS_REQUEST =
  'app/EditInterventionPage/DELETE_QUESTIONS_REQUEST';
export const DELETE_QUESTIONS_SUCCESS =
  'app/EditInterventionPage/DELETE_QUESTIONS_SUCCESS';
export const DELETE_QUESTIONS_ERROR =
  'app/EditInterventionPage/DELETE_QUESTIONS_ERROR';

export const GROUP_QUESTIONS_REQUEST =
  'app/EditInterventionPage/GROUP_QUESTIONS_REQUEST';
export const GROUP_QUESTIONS_SUCCESS =
  'app/EditInterventionPage/GROUP_QUESTIONS_SUCCESS';
export const GROUP_QUESTIONS_ERROR =
  'app/EditInterventionPage/GROUP_QUESTIONS_ERROR';

export const SHARE_QUESTIONS_TO_RESEARCHERS_REQUEST =
  'app/EditInterventionPage/SHARE_QUESTIONS_TO_RESEARCHERS_REQUEST';
export const SHARE_QUESTIONS_TO_RESEARCHERS_SUCCESS =
  'app/EditInterventionPage/SHARE_QUESTIONS_TO_RESEARCHERS_SUCCESS';
export const SHARE_QUESTIONS_TO_RESEARCHERS_ERROR =
  'app/EditInterventionPage/SHARE_QUESTIONS_TO_RESEARCHERS_ERROR';

export const CHANGE_GROUP_NAME_REQUEST =
  'app/EditInterventionPage/CHANGE_GROUP_NAME_REQUEST';
export const CHANGE_GROUP_NAME_SUCCESS =
  'app/EditInterventionPage/CHANGE_GROUP_NAME_SUCCESS';
export const CHANGE_GROUP_NAME_ERROR =
  'app/EditInterventionPage/CHANGE_GROUP_NAME_ERROR';

export const GET_QUESTION_GROUPS_REQUEST =
  'app/EditInterventionPage/GET_QUESTION_GROUPS_REQUEST';
export const GET_QUESTION_GROUPS_SUCCESS =
  'app/EditInterventionPage/GET_QUESTION_GROUPS_SUCCESS';
export const GET_QUESTION_GROUPS_ERROR =
  'app/EditInterventionPage/GET_QUESTION_GROUPS_ERROR';

export const CREATE_QUESTION_IN_GROUP =
  'app/EditInterventionPage/CREATE_QUESTION_IN_GROUP';

export const SAVED_ACTIONS = [
  GET_QUESTION_GROUPS_SUCCESS,
  GET_QUESTION_GROUPS_ERROR,
  CHANGE_GROUP_NAME_ERROR,
  CHANGE_GROUP_NAME_SUCCESS,
  SHARE_QUESTIONS_TO_RESEARCHERS_SUCCESS,
  SHARE_QUESTIONS_TO_RESEARCHERS_ERROR,
  GROUP_QUESTIONS_SUCCESS,
  GROUP_QUESTIONS_ERROR,
  COPY_QUESTIONS_ERROR,
  COPY_QUESTIONS_SUCCESS,
  DELETE_QUESTIONS_ERROR,
  DELETE_QUESTIONS_SUCCESS,
];

export const SAVING_ACTIONS = [
  GET_QUESTION_GROUPS_REQUEST,
  GROUP_QUESTIONS_REQUEST,
  SHARE_QUESTIONS_TO_RESEARCHERS_REQUEST,
  COPY_QUESTIONS_REQUEST,
  DELETE_QUESTIONS_REQUEST,
  CHANGE_GROUP_NAME_REQUEST,
];
