export const CREATE_INTERVENTION_REQUEST =
  'app/Dashboard/CREATE_INTERVENTION_REQUEST';
export const CREATE_INTERVENTION_SUCCESS =
  'app/Dashboard/CREATE_INTERVENTION_SUCCESS';
export const CREATE_INTERVENTION_ERROR =
  'app/Dashboard/CREATE_INTERVENTION_ERROR';
