export const FETCH_REPORTS_REQUEST = 'app/Dashboard/FETCH_REPORTS_REQUEST';
export const FETCH_REPORTS_SUCCESS = 'app/Dashboard/FETCH_REPORTS_SUCCESS';
export const FETCH_REPORTS_ERROR = 'app/Dashboard/FETCH_REPORTS_ERROR';

export const FETCH_INTERVENTIONS_REQUEST =
  'app/Dashboard/FETCH_INTERVENTIONS_REQUEST';
export const FETCH_INTERVENTIONS_SUCCESS =
  'app/Dashboard/FETCH_INTERVENTIONS_SUCCESS';
export const FETCH_INTERVENTIONS_ERROR =
  'app/Dashboard/FETCH_INTERVENTIONS_ERROR';

export const FETCH_LATEST_REPORT_REQUEST =
  'app/Dashboard/FETCH_LATEST_REPORT_REQUEST';
export const FETCH_LATEST_REPORT_SUCCESS =
  'app/Dashboard/FETCH_LATEST_REPORT_SUCCESS';
export const FETCH_LATEST_REPORT_ERROR =
  'app/Dashboard/FETCH_LATEST_REPORT_ERROR';

export const TOGGLE_NOTIFICATIONS_REQUEST =
  'app/Dashboard/TOGGLE_NOTIFICATIONS_REQUEST';
export const TOGGLE_NOTIFICATIONS_SUCCESS =
  'app/Dashboard/TOGGLE_NOTIFICATIONS_SUCCESS';
export const TOGGLE_NOTIFICATIONS_ERROR =
  'app/Dashboard/TOGGLE_NOTIFICATIONS_ERROR';

export const PER_PAGE = 10;
