export const ON_UNREAD_NOTIFICATIONS_FETCHED_RECEIVE =
  'app/Notifications/ON_UNREAD_NOTIFICATIONS_FETCHED_RECEIVE';

export const ON_NEW_NOTIFICATION_RECEIVE =
  'app/Notifications/ON_NEW_NOTIFICATION_RECEIVE';
