export const ADD_NEW_EVENT = 'app/TLFB/ADD_NEW_EVENT';
export const ADD_NEW_EVENT_SUCCESS = 'app/TLFB/ADD_NEW_EVENT_SUCCESS';
export const ADD_NEW_EVENT_ERROR = 'app/TLFB/ADD_NEW_EVENT_ERROR';
export const EDIT_EVENT_NAME_REQUEST = 'app/TLFB/EDIT_EVENT_NAME_REQUEST';
export const EDIT_EVENT_NAME_ERROR = 'app/TLFB/EDIT_EVENT_NAME_ERROR';
