export const ADD_NEW_EVENT_REQUEST = 'app/TLFB/ADD_NEW_EVENT_REQUEST';
export const ADD_NEW_EVENT_SUCCESS = 'app/TLFB/ADD_NEW_EVENT_SUCCESS';
export const ADD_NEW_EVENT_ERROR = 'app/TLFB/ADD_NEW_EVENT_ERROR';
export const EDIT_EVENT_NAME_REQUEST = 'app/TLFB/EDIT_EVENT_NAME_REQUEST';
export const EDIT_EVENT_NAME_ERROR = 'app/TLFB/EDIT_EVENT_NAME_ERROR';
export const EDIT_EVENT_NAME_SUCCESS = 'app/TLFB/EDIT_EVENT_NAME_SUCCESS';
export const DELETE_EVENT_REQUEST = 'app/TLFB/DELETE_EVENT_REQUEST';
export const DELETE_EVENT_ERROR = 'app/TLFB/DELETE_EVENT_ERROR';
export const DELETE_EVENT_SUCCESS = 'app/TLFB/DELETE_EVENT_SUCCESS';
export const ADD_TLFB_QUESTION_ANSWER_REQUEST =
  'app/TLFB/ADD_TLFB_QUESTION_ANSWER_REQUEST';
export const ADD_TLFB_QUESTION_ANSWER_ERROR =
  'app/TLFB/ADD_TLFB_QUESTION_ANSWER_ERROR';
export const ADD_TLFB_QUESTION_ANSWER_SUCCESS =
  'app/TLFB/ADD_TLFB_QUESTION_ANSWER_SUCCESS';
export const EDIT_TLFB_QUESTION_ANSWER_REQUEST =
  'app/TLFB/EDIT_TLFB_QUESTION_ANSWER_REQUEST';
export const EDIT_TLFB_QUESTION_ANSWER_ERROR =
  'app/TLFB/EDIT_TLFB_QUESTION_ANSWER_ERROR';
export const EDIT_TLFB_QUESTION_ANSWER_SUCCESS =
  'app/TLFB/EDIT_TLFB_QUESTION_ANSWER_SUCCESS';
export const FETCH_CALENDAR_DATA_REQUEST =
  'app/TLFB/FETCH_CALENDAR_DATA_REQUEST';
export const FETCH_CALENDAR_DATA_ERROR = 'app/TLFB/FETCH_CALENDAR_DATA_ERROR';
export const FETCH_CALENDAR_DATA_SUCCESS =
  'app/TLFB/FETCH_CALENDAR_DATA_SUCCESS';
