export const OPEN_CONVERSATION = 'app/LiveChat/OPEN_CONVERSATION';
export const CLOSE_CONVERSATION = 'app/LiveChat/CLOSE_CONVERSATION';

export const FETCH_CONVERSATIONS_REQUEST =
  'app/LiveChat/FETCH_CONVERSATIONS_REQUEST';
export const FETCH_CONVERSATIONS_SUCCESS =
  'app/LiveChat/FETCH_CONVERSATIONS_SUCCESS';
export const FETCH_CONVERSATIONS_ERROR =
  'app/LiveChat/FETCH_CONVERSATIONS_ERROR';

export const FETCH_CONVERSATION_MESSAGES_REQUEST =
  'app/LiveChat/FETCH_CONVERSATION_MESSAGES_REQUEST';
export const FETCH_CONVERSATION_MESSAGES_SUCCESS =
  'app/LiveChat/FETCH_CONVERSATION_MESSAGES_SUCCESS';
export const FETCH_CONVERSATION_MESSAGES_ERROR =
  'app/LiveChat/FETCH_CONVERSATION_MESSAGES_ERROR';

export const ON_MESSAGE_SENT_RECEIVE = 'app/LiveChat/ON_MESSAGE_SENT_RECEIVE';

export const MARK_MESSAGE_READ_LOCALLY =
  'app/LiveChat/MARK_MESSAGE_READ_LOCALLY';
export const ON_MESSAGE_READ_RECEIVE = 'app/LiveChat/ON_MESSAGE_READ_RECEIVE';

export const SET_CREATING_CONVERSATION =
  'app/LiveChat/SET_CREATING_CONVERSATION';
export const ON_CONVERSATION_CREATED_RECEIVE =
  'app/LiveChat/ON_CONVERSATION_CREATED_RECEIVE';
export const SET_GUEST_INTERLOCUTOR_ID =
  'app/LiveChat/SET_GUEST_INTERLOCUTOR_ID';

export const SET_ARCHIVING_CONVERSATION =
  'app/LiveChat/SET_ENDING_CONVERSATION';
export const ON_CONVERSATION_ARCHIVED_RECEIVE =
  'app/LiveChat/ON_CONVERSATION_ENDED_RECEIVE';

export const SET_NAVIGATOR_UNAVAILABLE =
  'app/LiveChat/SET_NAVIGATOR_UNAVAILABLE';

export const ON_NAVIGATOR_UNAVAILABLE_SETUP_RECEIVE =
  'app/LiveChat/ON_NAVIGATOR_UNAVAILABLE_SETUP_RECEIVE';
