export const OPEN_CONVERSATION = 'app/LiveChat/OPEN_CONVERSATION';
export const CLOSE_CONVERSATION = 'app/LiveChat/CLOSE_CONVERSATION';
export const READ_MESSAGE = 'app/LiveChat/READ_MESSAGE';

export const FETCH_CONVERSATIONS_REQUEST =
  'app/LiveChat/FETCH_CONVERSATIONS_REQUEST';
export const FETCH_CONVERSATIONS_SUCCESS =
  'app/LiveChat/FETCH_CONVERSATIONS_SUCCESS';
export const FETCH_CONVERSATIONS_ERROR =
  'app/LiveChat/FETCH_CONVERSATIONS_ERROR';

export const FETCH_CONVERSATION_MESSAGES_REQUEST =
  'app/LiveChat/FETCH_CONVERSATION_MESSAGES_REQUEST';
export const FETCH_CONVERSATION_MESSAGES_SUCCESS =
  'app/LiveChat/FETCH_CONVERSATION_MESSAGES_SUCCESS';
export const FETCH_CONVERSATION_MESSAGES_ERROR =
  'app/LiveChat/FETCH_CONVERSATION_MESSAGES_ERROR';

export const ON_MESSAGE_SENT_RECEIVE = 'app/LiveChat/ON_MESSAGE_SENT_RECEIVE';
export const ON_MESSAGE_READ_RECEIVE = 'app/LiveChat/ON_MESSAGE_READ_RECEIVE';
export const ON_CONVERSATION_CREATED_RECEIVE =
  'app/LiveChat/ON_CONVERSATION_CREATED_RECEIVE';
