export enum AnswerType {
  SINGLE = 'Answer::Single',
  MULTIPLE = 'Answer::Multiple',
  FREE_RESPONSE = 'Answer::FreeResponse',
  DATE = 'Answer::Date',
  NAME = 'Answer::Name',
  CURRENCY = 'Answer::Currency',
  NUMBER = 'Answer::Number',
  GRID = 'Answer::Grid',
  SLIDER = 'Answer::Slider',
  INFORMATION = 'Answer::Information',
  EXTERNAL_LINK = 'Answer::ExternalLink',
  FEEDBACK = 'Answer::Feedback',
  PARTICIPANT_REPORT = 'Answer::ParticipantReport',
  THIRD_PARTY = 'Answer::ThirdParty',
  PHONE = 'Answer::Phone',
}
