export const FETCH_INTERVENTIONS_REQUEST =
  'app/Dashboard/FETCH_INTERVENTIONS_REQUEST';
export const FETCH_INTERVENTIONS_SUCCESS =
  'app/Dashboard/FETCH_INTERVENTIONS_SUCCESS';
export const FETCH_INTERVENTIONS_ERROR =
  'app/Dashboard/FETCH_INTERVENTIONS_ERROR';

export const COPY_INTERVENTION_REQUEST =
  'app/Dashboard/COPY_INTERVENTION_REQUEST';
export const COPY_INTERVENTION_SUCCESS =
  'app/Dashboard/COPY_INTERVENTION_SUCCESS';
export const COPY_INTERVENTION_ERROR = 'app/Dashboard/COPY_INTERVENTION_ERROR';

export const ARCHIVE_INTERVENTION_REQUEST =
  'app/Dashboard/ARCHIVE_INTERVENTION_REQUEST';
export const ARCHIVE_INTERVENTION_SUCCESS =
  'app/Dashboard/ARCHIVE_INTERVENTION_SUCCESS';
export const ARCHIVE_INTERVENTION_ERROR =
  'app/Dashboard/ARCHIVE_INTERVENTION_ERROR';

export const IMPORT_INTERVENTION_REQUEST =
  'app/Dashboard/IMPORT_INTERVENTION_REQUEST';
export const IMPORT_INTERVENTION_SUCCESS =
  'app/Dashboard/IMPORT_INTERVENTION_SUCCESS';
export const IMPORT_INTERVENTION_ERROR =
  'app/Dashboard/IMPORT_INTERVENTION_ERROR';

export const REFETCH_INTERVENTIONS = 'app/Dashboard/REFETCH_INTERVENTIONS';
