export const FETCH_INTERVENTIONS_REQUEST =
  'app/Dashboard/FETCH_INTERVENTIONS_REQUEST';
export const FETCH_INTERVENTIONS_SUCCESS =
  'app/Dashboard/FETCH_INTERVENTIONS_SUCCESS';
export const FETCH_INTERVENTIONS_ERROR =
  'app/Dashboard/CREATE_INTERVENTION_ERROR';
