#name: Integration tests
#on:
#  pull_request_review:
#    branches:
#      - dev
#      - master
#    types: [submitted]
#
#jobs:
#  integration:
#    name: Cypress
#    runs-on: ubuntu-latest
#    env:
#      CYPRESS_API_URL: ${{ secrets.CYPRESS_API_URL }}
#      CYPRESS_ADMIN_EMAIL: ${{ secrets.CYPRESS_ADMIN_EMAIL }}
#      CYPRESS_ADMIN_PASSWORD: ${{ secrets.CYPRESS_ADMIN_PASSWORD }}
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up Node
#        uses: actions/setup-node@v1
#        with:
#          node-version: '14'
#
#      - name: Cache node modules
#        uses: actions/cache@v2
#        with:
#          path: |
#            ~/.npm
#            ~/.cache
#          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
#          restore-keys: |
#            ${{ runner.os }}-build-${{ env.cache-name }}-
#            ${{ runner.os }}-build-
#            ${{ runner.os }}--
#
#      - name: Install Dependencies
#        run: npm ci
#
#      - name: Run app and wait for server
#        run: npm start & npx wait-on http://localhost:4200
#
#      - name: Run integration tests
#        run: npm run cy:test
