export const HEADER_HEIGHT = 72;
export const INTERLOCUTOR_INFO_HEIGHT = 93.7;
export const NO_CONVERSATIONS_INFO_MAX_WIDTH = 392;
export const NO_CONVERSATION_OPENED_INFO_MAX_WIDTH = 194;

export const MESSAGE_TIMESTAMP_REFRESH_PERIOD = 60000;
